apiVersion: v1
kind: Service
metadata:
  name: metal-exporter
  labels:
    app: metal-exporter
spec:
  ports:
    - name: metrics
      port: 9080
      targetPort: metrics
  selector:
    app: metal-exporter
